service: workers-poc
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"

provider:
  name: aws
  environment:
    STAGE: dev
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    REGION: "us-east-1"
  ecr:
    images:
      workers-image:
        path: ./

functions:
  workers:
    image:
      name: workers-image

  worker_1:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_1
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_1
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_2:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_2
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_2
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_3:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_3
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_3
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_4:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_4
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_4
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_5:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_5
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_5
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_6:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_6
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_6
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_7:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_7
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_7
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_8:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_8
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_8
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_9:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_9
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_9
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_10:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_10
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_10
      - Effect: "Allow"
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

  worker_cron:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_cron

plugins:
  - serverless-iam-roles-per-function
