service: workers-poc
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  environment:
    STAGE: dev
  ecr:
    images:
      workers-image:
        path: ./

functions:
  workers:
    image:
      name: workers-image
