service: workers-poc
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  environment:
    STAGE: dev
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    REGION: 'us-east-1'
  ecr:
    images:
      workers-image:
        path: ./

functions:
  workers:
    image:
      name: workers-image

  worker_1:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_1

  worker_2:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_2

  worker_3:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_3

  worker_4:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_4

  worker_5:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_5

  worker_6:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_6

  worker_7:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_7

  worker_8:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_8

  worker_9:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_9

  worker_10:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:${env:REGION}:${env:ACCOUNT_ID}:worker_10
