service: robots-poc
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  environment:
    STAGE: dev
  ecr:
    images:
      robots-image:
        path: ./

functions:
  robots:
    image:
      name: robots-image

  robot_01:
    image:
      name: robots-image

  robot_02:
    image:
      name: robots-image

  robot_03:
    image:
      name: robots-image

  robot_04:
    image:
      name: robots-image

  robot_05:
    image:
      name: robots-image

  robot_06:
    image:
      name: robots-image

  robot_07:
    image:
      name: robots-image

  robot_08:
    image:
      name: robots-image

  robot_09:
    image:
      name: robots-image

  robot_10:
    image:
      name: robots-image
