service: workers-poc
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  environment:
    STAGE: dev
  ecr:
    images:
      workers-image:
        path: ./

functions:
  workers:
    image:
      name: workers-image

  worker_01:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_01

  worker_02:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_02

  worker_03:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_03

  worker_04:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_04

  worker_05:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_05

  worker_06:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_06

  worker_07:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_07

  worker_08:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_08

  worker_09:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_09

  worker_10:
    image:
      name: workers-image
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:986806511625:worker_10